export enum ChargePointErrorCode {
  NO_ERROR = 'NoError',
  CONNECTOR_LOCK_FAILURE = 'ConnectorLockFailure',
  EV_COMMUNICATION_ERROR = 'EVCommunicationError',
  GROUND_FAILURE = 'GroundFailure',
  HIGH_TEMPERATURE = 'HighTemperature',
  INTERNAL_ERROR = 'InternalError',
  LOCAL_LIST_CONFLICT = 'LocalListConflict',
  OTHER_ERROR = 'OtherError',
  OVER_CURRENT_FAILURE = 'OverCurrentFailure',
  OVER_VOLTAGE = 'OverVoltage',
  POWER_METER_FAILURE = 'PowerMeterFailure',
  POWER_SWITCH_FAILURE = 'PowerSwitchFailure',
  READER_FAILURE = 'ReaderFailure',
  RESET_FAILURE = 'ResetFailure',
  UNDER_VOLTAGE = 'UnderVoltage',
  WEAK_SIGNAL = 'WeakSignal',
}
