FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache dumb-init curl

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .

EXPOSE 3001 8081

ENTRYPOINT ["dumb-init", "--"]

CMD ["npm", "run", "start:dev"]
